language: ruby
rvm:
  - "1.8.7"
  - "1.9.3"
  - "2.1.1"
env:
  - MODULES=software
  - MODULES=all
# Testing with all modules is a heavy test, so we'll do it only once,
# with most modern version of Ruby
matrix:
  exclude:
    - rvm: "1.8.7"
      env: MODULES=all
    - rvm: "1.9.3"
      env: MODULES=all
before_script: "touch proprietary/agreed"
script: "./configure --modules=$MODULES && make && ./tests_functional; ./tests_simulate"
