Document: einarc
Title: Debian einarc Manual
Author: Inquisitor team
Abstract: This manual describes what einarc is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/einarc/einarc.sgml.gz

Format: postscript
Files: /usr/share/doc/einarc/einarc.ps.gz

Format: text
Files: /usr/share/doc/einarc/einarc.text.gz

Format: HTML
Index: /usr/share/doc/einarc/html/index.html
Files: /usr/share/doc/einarc/html/*.html
