#!/bin/sh

RELEASEDIR=$HOME
VERSION=`sed 's/Einarc v//' <../VERSION`

rm -rf $RELEASEDIR/einarc-$VERSION
svn export https://inq.svn.sourceforge.net/svnroot/inq/trunk/client/lib/einarc $RELEASEDIR/einarc-$VERSION
cd $RELEASEDIR
rm -rf einarc-$VERSION/maintenance
tar -cjvf $RELEASEDIR/einarc-$VERSION.tar.bz2 einarc-$VERSION
